swagger: "2.0"
info:
  description: "Essa é a documentação da API da Memory Line para uso do grupo da faculdade"
  version: "1.0.0"
  title: "TecHxHunt Memory Line"
host: "Unknown:5000"
tags:
  - name: "memory line"
  - name: "moment in memory line"
  - name: "share memory line"
schemes:
  - "http"

paths:
  /:
    post:
      tags:
      - "memory line"
      summary: "Insere uma nova memory line"
      description: "O usuário não precisa mandar nenhuma informação, automaticamente a memory line é criada com o nome untitled e as outras informações tiradas do usuário que a enviou"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - name: "user_id"
          in: "header"
          required: true
          type: "string"
      responses:
        200:
          description: "Não houve nenhum erro no cadastro de memory line"
          schema:
            properties:
                message:
                  type: string
                  description: "Cadastro feito com sucesso"
  /all:
    get:
      tags:
        - "memory line"
      summary: "Retorna as memory line do usuário (privadas ou públicas)"
      produces:
      - "application/json"
      parameters:
        - name: "user_id"
          in: "header"
          required: true
          type: "string"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/AllMemoryLine"
  /{id_memory_line}:
    get:
      tags:
        - "memory line"
      summary: "Retorna os campeonatos de uma empresa ! Necessário Cookie"
      description: "Retorna os campeonatos de uma empresa"
      parameters:
      - name: "id_memory_line"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/InsertMachineData"
    delete:
      tags:
        - "memory line"
      summary: "Retorna os campeonatos de uma empresa ! Necessário Cookie"
      description: "Retorna os campeonatos de uma empresa"
      parameters:
      - name: "id_memory_line"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/InsertMachineData"
    put:
      tags:
        - "memory line"
      summary: "Retorna os campeonatos de uma empresa ! Necessário Cookie"
      description: "Retorna os campeonatos de uma empresa"
      parameters:
      - name: "id_memory_line"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/InsertMachineData"
    post:
      tags:
        - "memory line"
      summary: "Retorna os campeonatos de uma empresa ! Necessário Cookie"
      description: "Retorna os campeonatos de uma empresa"
      parameters:
      - name: "id_memory_line"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/InsertMachineData"
  
  /{id_memory_line}/{id_moment}:
    delete:
      tags:
        - "moment in memory line"
      summary: "Retorna os campeonatos de uma empresa ! Necessário Cookie"
      description: "Retorna os campeonatos de uma empresa"
      parameters:
      - name: "id_memory_line"
        in: "path"
        required: true
        type: "string"
      - name: "id_moment"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/InsertMachineData"
    put:
      tags:
        - "moment in memory line"
      summary: "Retorna os campeonatos de uma empresa ! Necessário Cookie"
      description: "Retorna os campeonatos de uma empresa"
      parameters:
      - name: "id_memory_line"
        in: "path"
        required: true
        type: "string"
      - name: "id_moment"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/InsertMachineData"
            
  /{id_memory_line}/share:
    get:
      tags:
        - "share memory line"
      summary: "Retorna os campeonatos de uma empresa ! Necessário Cookie"
      description: "Retorna os campeonatos de uma empresa"
      parameters:
      - name: "id_memory_line"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/InsertMachineData"
  /{id_memory_line}/invite/{id_user}:
    get:
      tags:
        - "share memory line"
      summary: "Retorna os campeonatos de uma empresa ! Necessário Cookie"
      description: "Retorna os campeonatos de uma empresa"
      parameters:
      - name: "id_memory_line"
        in: "path"
        required: true
        type: "string"
      - name: "id_user"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/InsertMachineData"
  
definitions:
  AllMemoryLine:
    type: array
    items:
      type: object
      properties:
        idMemoryLine:
          description: "Id da memory line como String"
          type: string
        nameMemoryLine:
          description: "Id da memory line como String"
          type: string
        participants:
          description: "Id da memory line como String"
          type: string
        quantityMoments:
          description: ""
          type: integer
        urlProfileImage:
          description: "Id da memory line como String"
          type: string
        lastTimeUpdate:
          example: "1995-09-07T10:40:52Z"
          format: date-time
          type: string
        creationDate:
          example: "1995-09-07T10:40:52Z"
          format: date-time
          type: string
  MemoryLine:
    type: object
    properties:
      nomeMemorieline:
        description: "Data da Medição"
        type: string
  DateMetricMachineData:
    type: object
    properties:
      date:
        description: "Data da Medição"
        type: string
  InsertMachineData:
    type: object
    properties:
      idMachine:
        description: "Placa Mãe"
        type: string
      motherBoard:
        description: "Placa Mãe"
        type: string
      os:
        description: "Sistema Operacional"
        type: string
      manufacturer:
        description: "Fabricante"
        type: string
      model:
        description: "Modelo"
        type: string
